@extends('layouts.principal')
@section('conteudo')
    <h3>Departamentos</h3>
    <ul>
        <li>PC</li>
        <li>Notebook</li>
        <li>Mouse</li>
        <li>Camisetas</li>
    </ul>
@endsection